Not working. Database changes

diff --git a/bot b/bot
--- a/bot
+++ b/bot
@@ -21,8 +21,8 @@ then
     MINOR=${VERSION_ARRAY[1]}
     PATCH=${VERSION_ARRAY[2]}
 
-    if [ "$MAJOR" -lt 3 ] || ([ "$MAJOR" -eq 3 ] && [ "$MINOR" -lt 11 ]); then
-        echo "You cannot run this script. Python version is too old. (Python 3.11 and above, you have $VERSION) You can download Python 3.11 at https://python.org"
+    if [ "$MAJOR" -lt 3 ] || ([ "$MAJOR" -eq 3 ] && [ "$MINOR" -lt 12 ]); then
+        echo "You cannot run this script. Python version is too old. (Python 3.12 and above, you have $VERSION) You can download Python 3.12 at https://python.org"
         exit 1
     else
         . "$DIR/bin/activate" &> /dev/null
@@ -34,7 +34,7 @@ then
             
             if [ "$OSTYPE" = "linux-gnu" ]
             then 
-                sudo apt install python3.11-venv
+                sudo apt install python3.12-venv
                 sudo apt-get -y install flac
             fi
 
